# Addition program created without any help by me:

a= input("Enter the First Number - ")
b= input("Enter the Second Number - ")
c=int(a)
d=int(b)
e=c+d
print("The sum of two numbers is : ")
print(e)


# More refined Version of it :
a= input("Enter the first number - ")
b = input("Enter the second Number - ")
a=int(a)
b=int(b)
c= a+b
print("The sum of two numbers is - ",c)


# Refined version of it :
a= int(input("Enter the first Number - "))
b= int(input ("Enter the second Number - "))
print("The sum of two numbers is -",a+b)


# New refined version of add :
a, b = input("Enter the two numbers of your choise :").split()
print(f"The sum of two numbers is : {int(a)+ int(b)}")

# The map() function automatically applies int() to every item generated by .split().
# Best approach for multiple inline numbers
a, b = map(int, input("Enter the two numbers of your choice: ").split())  # The map() function applies a specific action to every item in a list. Here, it applies int() (integer conversion) to each string piece.
print(f"The sum of two numbers is : {a + b}")
